import type { PrintLayoutSettings } from '../print/PrintLayoutSettings';
import type { PrintPageBoundary } from '../print/PrintPaginator';

export interface BackgroundPaginationInput {
  html: string;
  css: string;
  layout: PrintLayoutSettings;
  marginImageSources: Record<string, string>;
  /** Guides use the same renderer but do not reject transient blank pages. */
  purpose?: 'export' | 'guides';
}

export type BackgroundPaginationResult = {
  type: 'clear-writer-export-result';
  requestId: string;
  status: 'rendered' | 'degraded' | 'stale';
  html: string;
  /** CSS generated by Paged.js for this exact HTML/page-setup pair. */
  paginationCss: string;
  /** Physical-page boundaries from the same isolated Paged.js render. */
  pageBoundaries: readonly PrintPageBoundary[];
  error?: string;
};

/** Paginates in a separate document so Paged.js cannot affect the app preview. */
export class BackgroundExportPaginator {
  async paginate(input: BackgroundPaginationInput, signal?: AbortSignal): Promise<BackgroundPaginationResult> {
    if (signal?.aborted) throw new DOMException('Background pagination was cancelled.', 'AbortError');
    const requestId = crypto.randomUUID();
    const frame = document.createElement('iframe');
    frame.setAttribute('aria-hidden', 'true');
    frame.tabIndex = -1;
    frame.style.cssText = 'position:fixed;left:-100000px;top:0;width:1024px;height:1px;border:0;visibility:hidden;pointer-events:none;';

    // The current page can be an embedded test fixture or another host route.
    // Resolve from this bundled module so both Vite development and a relative
    // production base load the application's entry document.
    const frameUrl = new URL(
      import.meta.env.DEV ? '../../index.html' : '../index.html',
      import.meta.url
    );
    frameUrl.searchParams.set('export-frame', 'true');
    frame.src = frameUrl.toString();

    try {
      await new Promise<void>((resolve, reject) => {
        const timeout = window.setTimeout(() => {
          cleanup();
          reject(new Error('PDF export renderer did not load.'));
        }, 15_000);
        const cleanup = () => {
          window.clearTimeout(timeout);
          window.removeEventListener('message', receiveReady);
          signal?.removeEventListener('abort', receiveAbort);
        };
        const receiveAbort = () => {
          cleanup();
          reject(new DOMException('Background pagination was cancelled.', 'AbortError'));
        };
        const receiveReady = (event: MessageEvent<{ type?: string }>) => {
          if (event.origin !== window.location.origin || event.source !== frame.contentWindow) return;
          if (event.data?.type !== 'clear-writer-export-ready') return;
          cleanup();
          resolve();
        };
        window.addEventListener('message', receiveReady);
        signal?.addEventListener('abort', receiveAbort, { once: true });
        frame.addEventListener('error', () => {
          cleanup();
          reject(new Error('PDF export renderer could not load.'));
        }, { once: true });
        document.body.appendChild(frame);
      });

      return await new Promise<BackgroundPaginationResult>((resolve, reject) => {
        const timeout = window.setTimeout(() => {
          cleanup();
          reject(new Error('PDF export pagination timed out.'));
        }, 30_000);
        const cleanup = () => {
          window.clearTimeout(timeout);
          window.removeEventListener('message', receiveResult);
          signal?.removeEventListener('abort', receiveAbort);
        };
        const receiveAbort = () => {
          cleanup();
          reject(new DOMException('Background pagination was cancelled.', 'AbortError'));
        };
        const receiveResult = (event: MessageEvent<BackgroundPaginationResult>) => {
          if (event.origin !== window.location.origin || event.source !== frame.contentWindow) return;
          if (event.data?.type !== 'clear-writer-export-result' || event.data.requestId !== requestId) return;
          cleanup();
          if (event.data.status === 'rendered') resolve(event.data);
          else reject(new Error(event.data.error ?? `PDF export pagination ${event.data.status}.`));
        };
        window.addEventListener('message', receiveResult);
        signal?.addEventListener('abort', receiveAbort, { once: true });
        frame.contentWindow?.postMessage({ type: 'clear-writer-export-request', requestId, input }, window.location.origin);
      });
    } finally {
      frame.remove();
    }
  }
}
