import { PreviewController } from '../preview';
import { state } from '../state';
import type { PaginationTransport, AssetResolver } from '../platform/types';

export function bootWorker(transport: PaginationTransport, assetResolver: AssetResolver) {
  document.body.classList.add('is-worker');
  const printStyles = document.createElement('style');
  printStyles.id = 'pdf-worker-print-styles';
  printStyles.setAttribute('data-clear-writer-print-style', '');
  document.head.appendChild(printStyles);
  const stage = document.getElementById('paged-stage')!;
  const previewController = new PreviewController(stage, assetResolver, { mode: 'paginated', unthrottledPagination: true });

  transport.onExecutePagination(async (payload) => {
    const {
      requestId,
      html,
      pageSetup,
      typographySetup,
      listSetup,
      tableSetup,
      projectMetadata
    } = payload;
    
    if (projectMetadata) state.setProjectMetadata(projectMetadata);
    
    if (typographySetup) {
      previewController.applyTypographySetup(typographySetup);
    }
    if (listSetup) {
      previewController.applyListSetup(listSetup);
    }
    if (tableSetup) {
      previewController.applyTableSetup(tableSetup);
    }
    
    if (pageSetup) {
      previewController.applyPageSetup(pageSetup);
    }

    try {
      await previewController.forceRender(html);
      applyWorkerPrintStyles(printStyles, pageSetup);
      await waitForExportAssets(stage);
      const pageCount = stage.querySelectorAll('.pagedjs_page').length;
      if (pageCount === 0) throw new Error('Pagination produced no printable pages.');
      transport.sendPaginationResult({ requestId, ok: true, pageCount });
    } catch (e) {
      console.error('Worker pagination failed', e);
      transport.sendPaginationResult({
        requestId,
        ok: false,
        error: e instanceof Error ? e.message : 'PDF pagination failed.'
      });
    }
  });
}

function applyWorkerPrintStyles(style: HTMLStyleElement, pageSetup: any) {
  const paperWidth = positiveNumber(pageSetup?.paperWidth, 210);
  const paperHeight = positiveNumber(pageSetup?.paperHeight, 297);
  style.textContent = `
    @page {
      size: ${paperWidth}mm ${paperHeight}mm;
      margin: 0;
    }

    /* This legacy worker may paginate a document, but never restyles its
       completed Paged.js pages. The page CSS generated by Paged.js owns all
       page, header, footer, and fragmentation geometry. */
  `;
}

function positiveNumber(val: any, fallback: number): number {
  const num = Number(val);
  return Number.isFinite(num) && num > 0 ? num : fallback;
}

function waitForExportAssets(container: HTMLElement): Promise<void> {
  const images = Array.from(container.querySelectorAll('img'));
  const promises = images.map(img => {
    if (img.complete) return Promise.resolve();
    return new Promise<void>(resolve => {
      img.onload = () => resolve();
      img.onerror = () => resolve();
    });
  });
  return Promise.all(promises).then(() => {});
}
